image: docker:18

services:
  - docker:19.03.0-dind

stages:
  - build
  - push

variables:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

Build:
  stage: build
  script:
    - docker ps
    - 'ls -al * '
    - 'pwd'

Push latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - master
  script:
    - docker images

Push tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - docker images