image: alpine:3.7

services:
  - docker:19.03.5-dind
  #- alpine:3.7

stages:
  - build
  - push

variables:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  IMGAGETAG: mschlech/beelogger-service:$CI_COMMIT_TAG

before_script:
   # - apk add  docker make go git
   # - make build
   # - make all-container

Build:
  stage: build
  script:
    - docker ps
    - 'ls -al * '
    - 'pwd'
    - 'echo "registry image : " + $CI_REGISTRY_IMAGE + " ci build token " + $CI_BUILD_TOKEN'
    - docker images
    - echo "Commit Tag -> " + CI_COMMIT_TAG
    - echo "login to docker hub -> " + IMAGETAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "pushing " + IMAGETAG
    - docker push $IMAGETAG
    #- docker login -u gitlab-ci-token --password-stdin $CI_BUILD_TOKEN
    - 'pwd'
    - echo "CI USER:" + $CI_REGISTRY_USER
    - echo "CI PASSWD:" + $CI_REGISTRY_PASSWORD
    - echo "CI REGISTRY:" + $CI_REGISTRY
    #docker tag local-image:tagname new-repo:tagname
    #docker push new-repo:tagname

Push latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - master
  script:
    - docker images

Push tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - docker images