image: golang:1.9

services:
  - docker:19.03.0-dind

stages:
  - build
  - push

variables:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  IMGAGETAG=: mschlech/beelogger-service:$CI_COMMIT_TAG

before_script:
    - make all-build
    - make all-container

Build:
  stage: build
  script:
    - docker ps
    - 'ls -al * '
    - 'pwd'
    - 'echo "registry image : " + $CI_REGISTRY_IMAGE + " ci build token " + $CI_BUILD_TOKEN'

    - echo "login to docker hub"
    - docker login -u gitlab-ci-token --password-stdin $CI_BUILD_TOKEN
    - 'pwd'
    - echo "CI USER:" + $CI_REGISTRY_USER
    - echo "CI PASSWD:" + $CI_REGISTRY_PASSWORD
    - echo "CI REGISTRY:" + $CI_REGISTRY
    - docker login -u gitlab-ci-token --password-stdin $CI_BUILD_TOKEN
    #docker tag local-image:tagname new-repo:tagname
    #docker push new-repo:tagname

Push latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - master
  script:
    - docker images

Push tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - docker images