image: alpine:3.7

services:
  - docker:19.03.5-dind
  #- alpine:3.7

stages:
  - build

variables:
   http_proxy: ""
   https_proxy: ""
   no_proxy: ""
   DOCKER_DRIVER: "overlay2"
   DOCKER_HOST: tcp://docker:2375
   IMGAGETAG: "mschlech/beelogger-service:$CI_COMMIT_TAG"

before_script:
    - apk add  docker make go git
    - make build
    - make all-container

Build:
  stage: build
  script:
    - docker ps
    - docker images
    #linux/amd64 linux/arm linux/arm64 linux/ppc64le linux/s390x
    - IMAGE="beelogger-service"
    - IMAGE_AMD64_TAG="beelogger-service:"+`docker images | awk  'NR==1 {print $2}' `
    # +"_"+$CI_BUILD_ID
    - 'ls -al * '
    - 'pwd'
    - 'echo "registry image : " + $CI_REGISTRY_IMAGE + \
            " ci build token " + $CI_BUILD_TOKEN + \
            " ci build ID " + $CI_BUILD_ID'
    - echo "Commit Tag -> " + $CI_COMMIT_TAG
    - echo "image amd64 -> " + $IMAGE_AMD64
    - echo "IMAGE_AMD64_TAG -> " + $IMAGE_AMD64_TAG
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "pushing "
    - docker push mschlech/$IMAGE $IMAGE_AMD64
    #- docker login -u gitlab-ci-token --password-stdin $CI_BUILD_TOKEN
    - 'pwd'
    - echo "CI USER:" + $CI_REGISTRY_USER
    - echo "CI PASSWD:" + $CI_REGISTRY_PASSWORD
    - echo "CI REGISTRY:" + $CI_REGISTRY
    #docker tag local-image:tagname new-repo:tagname
    #docker push new-repo:tagname

